# Generated by Django 4.2.29 on 2026-04-03 08:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('prospect', 'Prospect'), ('student', 'Student')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('communication_type', models.CharField(choices=[('intro_invitation', 'Introductory Session Invitation'), ('follow_up', 'Follow-up'), ('reminder', 'Reminder'), ('payment_request', 'Payment Request'), ('general', 'General')], default='general', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=100)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('standard_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive')], default='enrolled', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_date', models.DateTimeField()),
                ('channel', models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('referral', 'Referral'), ('walk_in', 'Walk-in')], default='website', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
            ],
            options={
                'ordering': ['-inquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('confirmation_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('interest_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('availability', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province_state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('enrollment_status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('prospect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to='core.prospect')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['email'], name='core_prospe_email_40cab8_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status'], name='core_prospe_status_4ba9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['created_at'], name='core_prospe_created_b3fe6a_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.enrollment'),
        ),
        migrations.AddField(
            model_name='interviewform',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_forms', to='core.coursesession'),
        ),
        migrations.AddField(
            model_name='interviewform',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_forms', to='core.student'),
        ),
        migrations.AddField(
            model_name='interviewform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_forms', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.prospect'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.coursesession'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.course'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='core_course_name_877481_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='core_course_status_f0af0e_idx'),
        ),
        migrations.AddField(
            model_name='communication',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.enrollment'),
        ),
        migrations.AddField(
            model_name='communication',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.prospect'),
        ),
        migrations.AddField(
            model_name='communication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='core_teache_email_0ea460_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='core_teache_status_cecf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='core_studen_email_26bdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_status'], name='core_studen_enrollm_9d4b34_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='core_paymen_invoice_6c7f35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['confirmation_status'], name='core_paymen_confirm_e0b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='core_invoic_issue_d_99a2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewform',
            index=models.Index(fields=['student', 'submitted_at'], name='core_interv_student_9e89b3_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewform',
            index=models.Index(fields=['teacher', 'submitted_at'], name='core_interv_teacher_1f036e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewform',
            index=models.Index(fields=['status'], name='core_interv_status_6f68a0_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['prospect', 'inquiry_date'], name='core_inquir_prospec_4f2059_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status'], name='core_inquir_status_a4c468_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['channel'], name='core_inquir_channel_04452a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='core_enroll_student_b14473_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['session', 'status'], name='core_enroll_session_262cea_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_enrollment'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['course', 'start_date'], name='core_course_course__948ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['teacher', 'start_date'], name='core_course_teacher_b8b219_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['status'], name='core_course_status_d89a09_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['recipient_type'], name='core_commun_recipie_24b93f_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['channel'], name='core_commun_channel_17b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type'], name='core_commun_communi_6ef0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['delivery_status'], name='core_commun_deliver_6d3fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['prospect'], name='core_commun_prospec_a90a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['student'], name='core_commun_student_3d74cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='communication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('recipient_type', 'prospect'), ('prospect__isnull', False), ('student__isnull', True)), models.Q(('recipient_type', 'student'), ('student__isnull', False), ('prospect__isnull', True)), _connector='OR'), name='communication_recipient_matches_type'),
        ),
    ]
