# Generated by Django 4.2.29 on 2026-04-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['prospect__first_name', 'prospect__last_name']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_email_26bdb0_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_record', to='core.prospect'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='core_studen_created_bc19b3_idx'),
        ),
    ]
