# Generated by Django 4.2.29 on 2026-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('tm_teacher', 'TM Teacher'), ('advance_technique_1', 'Advance Technique 1'), ('advance_technique_2', 'Advance Technique 2'), ('advance_technique_3', 'Advance Technique 3'), ('advance_technique_4', 'Advance Technique 4'), ('sidhi_administrator', 'Sidhi Administrator')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Teacher Specialization',
                'verbose_name_plural': 'Teacher Specializations',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='teacher',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.teacherspecialization'),
        ),
    ]
