# Generated by Django 4.2.29 on 2026-04-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_model_and_coursesession_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursesession',
            new_name='core_course_locatio_dea749_idx',
            old_name='core_course_locatio_9ef9fc_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='core_locati_name_65ac84_idx',
            old_name='core_locati_name_1aa503_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='core_locati_is_acti_d10f4b_idx',
            old_name='core_locati_is_acti_66e1de_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='core_locati_city_cc1b17_idx',
            old_name='core_locati_city_9ce40a_idx',
        ),
    ]
