# Generated by Django 4.2.29 on 2026-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_course_locatio_9ef9fc_idx_core_course_locatio_dea749_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__lte', models.F('fee_amount'))), name='enrollment_discount_lte_fee'),
        ),
    ]
