# Generated by Django 4.2.29 on 2026-04-06 23:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enrollment_enrollment_discount_lte_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_due_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('teacher_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('location_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ico_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement', to='core.enrollment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='core.location')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='core.teacher')),
            ],
            options={
                'ordering': ['-disbursement_date', '-id'],
                'indexes': [models.Index(fields=['teacher', 'disbursement_date'], name='core_disbur_teacher_e4c85e_idx'), models.Index(fields=['location', 'disbursement_date'], name='core_disbur_locatio_641059_idx'), models.Index(fields=['status'], name='core_disbur_status_cac47a_idx'), models.Index(fields=['disbursement_date'], name='core_disbur_disburs_a1c92d_idx')],
            },
        ),
    ]
