# Generated by Django 4.2.29 on 2026-04-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.student'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.prospect'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['student', 'inquiry_date'], name='core_inquir_student_bbaee0_idx'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(check=models.Q(('prospect__isnull', False), ('student__isnull', False), _connector='OR'), name='inquiry_requires_prospect_or_student'),
        ),
    ]
