# Generated by Django 4.2.29 on 2026-04-14

from django.db import migrations


def forwards(apps, schema_editor):
    Student = apps.get_model("core", "Student")
    Prospect = apps.get_model("core", "Prospect")
    Inquiry = apps.get_model("core", "Inquiry")
    Enrollment = apps.get_model("core", "Enrollment")

    # 1) Backfill Student.teacher from the most recent enrollment's session teacher.
    for student in Student.objects.filter(teacher__isnull=True).iterator():
        enrollment = (
            Enrollment.objects.filter(student_id=student.id)
            .select_related("session__teacher")
            .order_by("-enrollment_date", "-id")
            .first()
        )
        if enrollment and enrollment.session_id and enrollment.session.teacher_id:
            student.teacher_id = enrollment.session.teacher_id
            student.save(update_fields=["teacher", "updated_at"])

    # 2) Backfill Prospect.teacher from linked Student.teacher where possible.
    for prospect in Prospect.objects.filter(teacher__isnull=True).iterator():
        student = (
            Student.objects.filter(prospect_id=prospect.id)
            .exclude(teacher__isnull=True)
            .first()
        )
        if student:
            prospect.teacher_id = student.teacher_id
            prospect.save(update_fields=["teacher", "updated_at"])

    # 3) Backfill Inquiry.student from linked prospect->student conversion path.
    for inquiry in Inquiry.objects.filter(student__isnull=True).exclude(prospect__isnull=True).iterator():
        student = Student.objects.filter(prospect_id=inquiry.prospect_id).first()
        if student:
            inquiry.student_id = student.id
            inquiry.save(update_fields=["student", "updated_at"])


def backwards(apps, schema_editor):
    # Non-destructive migration: keep populated data on reverse.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_inquiry_student_prospect_teacher_student_teacher_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
