# Generated by Django 4.2.29 on 2026-04-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_backfill_owner_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.prospect')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.student')),
            ],
            options={
                'ordering': ['first_name', 'last_name', '-created_at'],
                'indexes': [models.Index(fields=['prospect'], name='core_contac_prospec_5eb04c_idx'), models.Index(fields=['student'], name='core_contac_student_84bdef_idx'), models.Index(fields=['owner'], name='core_contac_owner_i_656ec1_idx'), models.Index(fields=['is_primary'], name='core_contac_is_prim_d70e34_idx'), models.Index(fields=['created_at'], name='core_contac_created_643cbb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(check=models.Q(('prospect__isnull', False), ('student__isnull', False), _connector='OR'), name='contact_requires_prospect_or_student'),
        ),
    ]
