# Generated by Django 4.2.29 on 2026-04-20 02:08

import re

from django.db import migrations, models
import django.db.models.deletion


def _normalize_phone(value: str) -> str:
    return re.sub(r"\D+", "", value or "")


def _backfill_contact_identity(apps, schema_editor):
    Contact = apps.get_model("core", "Contact")
    Prospect = apps.get_model("core", "Prospect")
    Student = apps.get_model("core", "Student")

    # Normalize existing contact rows first.
    for contact in Contact.objects.all():
        changed = []
        legacy_phone = getattr(contact, "phone", None)
        if legacy_phone and not contact.phone_number:
            contact.phone_number = legacy_phone
            changed.append("phone_number")
        if not contact.last_name:
            contact.last_name = "Unknown"
            changed.append("last_name")
        if contact.email == "":
            contact.email = None
            changed.append("email")
        if contact.phone_number == "":
            contact.phone_number = None
            changed.append("phone_number")
        if changed:
            contact.save(update_fields=changed)

    def find_match(email: str, phone_number: str):
        email_value = (email or "").strip()
        if email_value:
            match = Contact.objects.filter(email__iexact=email_value).first()
            if match:
                return match

        phone_digits = _normalize_phone(phone_number)
        if phone_digits:
            for candidate in Contact.objects.exclude(phone_number__isnull=True).exclude(
                phone_number=""
            ):
                if _normalize_phone(candidate.phone_number) == phone_digits:
                    return candidate
        return None

    # Create/reuse contacts for all prospects from legacy identity fields.
    for prospect in Prospect.objects.all():
        first_name = (getattr(prospect, "first_name", "") or "").strip() or "Unknown"
        last_name = (getattr(prospect, "last_name", "") or "").strip() or "Unknown"
        email = (getattr(prospect, "email", "") or "").strip()
        phone_number = (getattr(prospect, "phone", "") or "").strip()

        contact = find_match(email=email, phone_number=phone_number)
        if contact is None:
            contact = Contact.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email or None,
                phone_number=phone_number or None,
            )
        else:
            updated_fields = []
            if first_name and not contact.first_name:
                contact.first_name = first_name
                updated_fields.append("first_name")
            if last_name and not contact.last_name:
                contact.last_name = last_name
                updated_fields.append("last_name")
            if email and not contact.email:
                contact.email = email
                updated_fields.append("email")
            if phone_number and not contact.phone_number:
                contact.phone_number = phone_number
                updated_fields.append("phone_number")
            if updated_fields:
                contact.save(update_fields=updated_fields)

        if prospect.contact_id != contact.id:
            prospect.contact_id = contact.id
            prospect.save(update_fields=["contact"])

    # Ensure every student links to the same contact as its prospect.
    for student in Student.objects.select_related("prospect"):
        contact_id = student.prospect.contact_id
        if contact_id and student.contact_id != contact_id:
            student.contact_id = contact_id
            student.save(update_fields=["contact"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_contact_contact_contact_requires_prospect_or_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["contact__first_name", "contact__last_name"]},
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prospect",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_record",
                to="core.contact",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="contact",
            name="contact_requires_prospect_or_student",
        ),
        migrations.RunPython(
            _backfill_contact_identity, migrations.RunPython.noop
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_prospec_5eb04c_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_student_84bdef_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_owner_i_656ec1_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_is_prim_d70e34_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="core_contac_created_643cbb_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="core_prospe_email_40cab8_idx",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="prospect",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="relationship",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="student",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="email",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="phone",
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="core_contac_email_800caf_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["phone_number"], name="core_contac_phone_n_02cc9a_idx"),
        ),
    ]
