# Generated by Django 4.2.29 on 2026-04-20 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_contact_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('transition_trigger', models.CharField(choices=[('intro_and_day20_completed', 'Intro training completed and Day 20 check-in completed')], default='intro_and_day20_completed', editable=False, max_length=50)),
                ('intro_completed_on', models.DateField(blank=True, editable=False, null=True)),
                ('day20_completed_on', models.DateField(blank=True, editable=False, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, editable=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meditator_profile', to='core.student')),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.CreateModel(
            name='MeditatorTransitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('transitioned', 'Transitioned to Meditator')], default='transitioned', editable=False, max_length=30)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('transition_trigger', models.CharField(choices=[('intro_and_day20_completed', 'Intro training completed and Day 20 check-in completed')], default='intro_and_day20_completed', editable=False, max_length=50)),
                ('intro_completed_on', models.DateField(blank=True, editable=False, null=True)),
                ('day20_completed_on', models.DateField(blank=True, editable=False, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, editable=False)),
                ('meditator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.meditator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditator_transition_events', to='core.student')),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
                'indexes': [models.Index(fields=['student', 'triggered_at'], name='core_medita_student_3d15fd_idx'), models.Index(fields=['transition_trigger'], name='core_medita_transit_360bfe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meditatortransitionevent',
            constraint=models.UniqueConstraint(fields=('student', 'event_type', 'transition_trigger'), name='unique_student_meditator_transition_event'),
        ),
        migrations.AddIndex(
            model_name='meditator',
            index=models.Index(fields=['transitioned_at'], name='core_medita_transit_493cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='meditator',
            index=models.Index(fields=['transition_trigger'], name='core_medita_transit_9bf237_idx'),
        ),
    ]
