# Generated by Django 4.2.29 on 2026-05-02 22:43

from django.db import migrations
from django.db.models import F


def validate_student_contact_alignment(apps, schema_editor):
    Student = apps.get_model("core", "Student")

    mismatches = list(
        Student.objects.exclude(contact_id__isnull=True)
        .exclude(prospect_id__isnull=True)
        .exclude(prospect__contact_id__isnull=True)
        .exclude(contact_id=F("prospect__contact_id"))
        .values_list("id", "contact_id", "prospect__contact_id")[:25]
    )
    if mismatches:
        details = ", ".join(
            f"Student#{student_id} (student.contact={student_contact_id}, prospect.contact={prospect_contact_id})"
            for student_id, student_contact_id, prospect_contact_id in mismatches
        )
        raise RuntimeError(
            "Student.contact mismatch detected. Resolve these rows before applying this migration: "
            f"{details}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_meditator_meditatortransitionevent_and_more'),
    ]

    operations = [
        migrations.RunPython(
            validate_student_contact_alignment,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['prospect__contact__first_name', 'prospect__contact__last_name']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
    ]
