# Generated by Django 4.2.29 on 2026-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_student_options_remove_student_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('bad_lead', 'Bad Lead'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['is_archived'], name='core_prospe_is_arch_fc9790_idx'),
        ),
    ]
