# Generated by Django 4.2.29 on 2026-05-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prospect_is_archived_alter_prospect_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='converted_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_prospects', to='core.student'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='converted_to_student',
            field=models.BooleanField(default=False),
        ),
    ]
