# Generated by Django 4.2.29 on 2026-05-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_prospect_converted_at_prospect_converted_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='converted_prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contacts', to='core.prospect'),
        ),
        migrations.AddField(
            model_name='contact',
            name='converted_to_prospect',
            field=models.BooleanField(default=False),
        ),
    ]
