# Generated by Django 4.2.29 on 2026-05-15 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_enforce_invoice_enrollment_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.teacher'),
        ),
        migrations.CreateModel(
            name='StudentGovernorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Governor', max_length=80)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governor_assignments', to='core.enrollment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governor_assignments', to='core.coursesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governor_assignments', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='core.teacher')),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
                'indexes': [models.Index(fields=['student', 'status'], name='core_studen_student_fa7482_idx'), models.Index(fields=['teacher', 'status'], name='core_studen_teacher_7d6ef0_idx'), models.Index(fields=['is_primary'], name='core_studen_is_prim_a9c9fc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentgovernorassignment',
            constraint=models.UniqueConstraint(fields=('student', 'teacher', 'enrollment', 'session', 'role'), name='unique_student_governor_assignment_signature'),
        ),
    ]
