# Generated by Django 4.2.29 on 2026-05-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_enrollment_course_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="converted_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="converted_prospect",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="converted_to_prospect",
        ),
    ]
