# Generated by Django 4.2.29 on 2026-05-17 16:47

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_contact_prospect_conversion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="course_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interested_prospects",
                to="core.course",
            ),
        ),
    ]
