# Generated by Django 4.2.29 on 2026-05-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_uuid_phase4_snapshot_legacy_int_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_code_833bcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_categor_1a40ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_is_acti_bcef00_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='additional_cost_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='base_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requires_residence',
        ),
        migrations.RemoveField(
            model_name='course',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='number_of_children_under_18',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.enrollment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.invoice'),
        ),
        migrations.DeleteModel(
            name='StudentGovernorAssignment',
        ),
    ]
