# Generated by Django 4.2.29 on 2026-05-20 17:42

from django.db import migrations, models
import django.db.models.deletion


def sync_uuid_ref_columns(apps, schema_editor):
    # Keep UUID reference columns aligned with legacy integer FK columns
    # before swapping FK bindings to to_field='uuid'.
    statements = [
        "UPDATE core_prospect SET contact_uuid_ref = (SELECT uuid FROM core_contact WHERE core_contact.id = core_prospect.contact_id) WHERE contact_id IS NOT NULL;",
        "UPDATE core_prospect SET converted_student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_prospect.converted_student_id) WHERE converted_student_id IS NOT NULL;",
        "UPDATE core_student SET prospect_uuid_ref = (SELECT uuid FROM core_prospect WHERE core_prospect.id = core_student.prospect_id) WHERE prospect_id IS NOT NULL;",
        "UPDATE core_inquiry SET prospect_uuid_ref = (SELECT uuid FROM core_prospect WHERE core_prospect.id = core_inquiry.prospect_id) WHERE prospect_id IS NOT NULL;",
        "UPDATE core_inquiry SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_inquiry.student_id) WHERE student_id IS NOT NULL;",
        "UPDATE core_enrollment SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_enrollment.student_id) WHERE student_id IS NOT NULL;",
        "UPDATE core_interviewform SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_interviewform.student_id) WHERE student_id IS NOT NULL;",
        "UPDATE core_meditator SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_meditator.student_id) WHERE student_id IS NOT NULL;",
        "UPDATE core_meditatortransitionevent SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_meditatortransitionevent.student_id) WHERE student_id IS NOT NULL;",
        "UPDATE core_meditatortransitionevent SET meditator_uuid_ref = (SELECT uuid FROM core_meditator WHERE core_meditator.id = core_meditatortransitionevent.meditator_id) WHERE meditator_id IS NOT NULL;",
        "UPDATE core_communication SET prospect_uuid_ref = (SELECT uuid FROM core_prospect WHERE core_prospect.id = core_communication.prospect_id) WHERE prospect_id IS NOT NULL;",
        "UPDATE core_communication SET student_uuid_ref = (SELECT uuid FROM core_student WHERE core_student.id = core_communication.student_id) WHERE student_id IS NOT NULL;",
    ]
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_studentgovernorassignment_enrollment_and_more'),
    ]

    operations = [
        migrations.RunPython(sync_uuid_ref_columns, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='communication',
                    new_name='core_commun_prospec_f2b3ce_idx',
                    old_name='core_commun_prospec_a90a4b_idx',
                ),
                migrations.RenameIndex(
                    model_name='communication',
                    new_name='core_commun_student_a91f46_idx',
                    old_name='core_commun_student_3d74cd_idx',
                ),
                migrations.RenameIndex(
                    model_name='enrollment',
                    new_name='core_enroll_student_d53a94_idx',
                    old_name='core_enroll_student_b14473_idx',
                ),
                migrations.RenameIndex(
                    model_name='inquiry',
                    new_name='core_inquir_prospec_ac3fd7_idx',
                    old_name='core_inquir_prospec_4f2059_idx',
                ),
                migrations.RenameIndex(
                    model_name='inquiry',
                    new_name='core_inquir_student_9a1a76_idx',
                    old_name='core_inquir_student_bbaee0_idx',
                ),
                migrations.RenameIndex(
                    model_name='interviewform',
                    new_name='core_interv_student_394cf0_idx',
                    old_name='core_interv_student_9e89b3_idx',
                ),
                migrations.RenameIndex(
                    model_name='meditatortransitionevent',
                    new_name='core_medita_student_d67f43_idx',
                    old_name='core_medita_student_3d15fd_idx',
                ),
                migrations.RemoveField(
                    model_name='communication',
                    name='prospect_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='communication',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='enrollment',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='inquiry',
                    name='prospect_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='inquiry',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='interviewform',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='meditator',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='meditatortransitionevent',
                    name='meditator_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='meditatortransitionevent',
                    name='student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='prospect',
                    name='contact_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='prospect',
                    name='converted_student_uuid_ref',
                ),
                migrations.RemoveField(
                    model_name='student',
                    name='prospect_uuid_ref',
                ),
                migrations.AlterField(
                    model_name='communication',
                    name='prospect',
                    field=models.ForeignKey(blank=True, db_column='prospect_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.prospect', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='communication',
                    name='student',
                    field=models.ForeignKey(blank=True, db_column='student_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='enrollment',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='inquiry',
                    name='prospect',
                    field=models.ForeignKey(blank=True, db_column='prospect_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.prospect', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='inquiry',
                    name='student',
                    field=models.ForeignKey(blank=True, db_column='student_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='interviewform',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='interview_forms', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='meditator',
                    name='student',
                    field=models.OneToOneField(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='meditator_profile', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='meditatortransitionevent',
                    name='meditator',
                    field=models.ForeignKey(db_column='meditator_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.meditator', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='meditatortransitionevent',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='meditator_transition_events', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='contact',
                    field=models.OneToOneField(blank=True, db_column='contact_uuid_ref', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect', to='core.contact', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='converted_student',
                    field=models.ForeignKey(blank=True, db_column='converted_student_uuid_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_prospects', to='core.student', to_field='uuid'),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='prospect',
                    field=models.OneToOneField(db_column='prospect_uuid_ref', on_delete=django.db.models.deletion.PROTECT, related_name='student_record', to='core.prospect', to_field='uuid'),
                ),
            ],
        ),
    ]
