# Generated by Django 4.2.29 on 2026-05-20 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_core_commun_prospec_a90a4b_idx_core_commun_prospec_f2b3ce_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='contact',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='inquiry',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='meditator',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='prospect',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='student',
                    name='id',
                ),
                migrations.AlterField(
                    model_name='communication',
                    name='prospect',
                    field=models.ForeignKey(blank=True, db_column='prospect_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.prospect'),
                ),
                migrations.AlterField(
                    model_name='communication',
                    name='student',
                    field=models.ForeignKey(blank=True, db_column='student_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='contact',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='enrollment',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='inquiry',
                    name='prospect',
                    field=models.ForeignKey(blank=True, db_column='prospect_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.prospect'),
                ),
                migrations.AlterField(
                    model_name='inquiry',
                    name='student',
                    field=models.ForeignKey(blank=True, db_column='student_uuid_ref', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='inquiry',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='interviewform',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='interview_forms', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='meditator',
                    name='student',
                    field=models.OneToOneField(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='meditator_profile', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='meditator',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='meditatortransitionevent',
                    name='meditator',
                    field=models.ForeignKey(db_column='meditator_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.meditator'),
                ),
                migrations.AlterField(
                    model_name='meditatortransitionevent',
                    name='student',
                    field=models.ForeignKey(db_column='student_uuid_ref', on_delete=django.db.models.deletion.CASCADE, related_name='meditator_transition_events', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='contact',
                    field=models.OneToOneField(blank=True, db_column='contact_uuid_ref', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect', to='core.contact'),
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='converted_student',
                    field=models.ForeignKey(blank=True, db_column='converted_student_uuid_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_prospects', to='core.student'),
                ),
                migrations.AlterField(
                    model_name='prospect',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='prospect',
                    field=models.OneToOneField(db_column='prospect_uuid_ref', on_delete=django.db.models.deletion.PROTECT, related_name='student_record', to='core.prospect'),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
