# Generated by Django 4.2.29 on 2026-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_contact_id_remove_inquiry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='delivery_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read'), ('bounced', 'Bounced')], default='queued', max_length=20),
        ),
    ]
