# Generated by Django 4.2.29 on 2026-08-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_inquiry_human_readable_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.inquiry'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['inquiry'], name='core_commun_inquiry_c1d2e3_idx'),
        ),
    ]
