# Generated by Django 4.2.29 on 2026-08-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_communication_inquiry_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_archived'], name='core_inquir_is_arch_b6eaaf_idx'),
        ),
    ]
